### PR TITLE
Fix: Header Component

### LINKED ISSUE #79: Fix Header Connection
Fix connection with mainGallery

### PR DESCRIPTION
**Pull request by Anastasiia0999**
- Changed subscribe
- Fixed bug with searching same model(macan and again macan for example)

### CODE REVIEW

**Review by PavelKundenko — APPROVED** [review]

**Review by MozdolevskyiMaksym — APPROVED** [review]

File: app/components/header/header-view.js [hunk 1]
```diff
@@ -68,4 +68,8 @@ export class HeaderView {
       const contactsElem = document.querySelector('#contacts');
       contactsElem.addEventListener('click', this.showContacts);
     }
+
+    clearInput = () => {
+      document.querySelector('.header__input').value = '';
```
Comment (so2niko) [inline app/components/header/header-view.js:73]: Can we remember this element into a property and not search each time when clearing the field?

**Review by so2niko — CHANGES_REQUESTED** [review]

File: app/components/header/header-view.js (hunk 1 above)
Comment (so2niko) [reply app/components/header/header-view.js:73]: Опоздал)
