### PR TITLE
fix-form

### LINKED ISSUE #103: Send order bug
image
I saw when send order

### PR DESCRIPTION
**Pull request by Winchestery**
accept-form fixed view fixed
index.html fixed
callMe changed to call-me

### CODE REVIEW

File: app/components/accept-form/form-model.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ export class FormModel {
     }, {});
     return {
       fullName: data['full-name'],
-      telNumber: data.telephone,
+      telNumber: data['telephone'],
```
Comment (rearchontis) [inline app/components/accept-form/form-model.js]: It is better to use [dot notation](https://eslint.org/docs/rules/dot-notation).
A tip: just run `npm run lint` or `eslint ./app/components/accept-form` or `npx eslint ./app` etc. Also you can use `eslint ./app --fix` to make eslint format some cases that it can be formatted, others will be showed as errors

**Review by OlehDrozdov — APPROVED** [review]

**Review by Anastasiia0999 — APPROVED** [review]
